#pragma once
/************************************************************************/
/*                禁止使用magic_enum进行直接转换                          */
/*                Error会使得g_bStop为True								*/
/*                Warning做提示作用，不影响切割							*/
/*                Info仅显示消息											*/
/************************************************************************/

// 错误
enum class ErrorCode
{
	ERROR_NONE = 0,
	// 系统
	ERROR_SYSTEM_,
	// 运动控制器
	ERROR_MC_CONNECTIONFAILED,
	ERROR_MC_HOMEFAILED,
	ERROR_MC_SETTINGFAILED,
	ERROR_MC_MOVEFAILED,
	// 激光器
	ERROR_LASER_CONNECTIONFAILED,
	ERROR_LASER_SETTINGFAILED,
	// 信号源
	ERROR_SIGNALSOURCE_CONNECTIONFAILED,
	ERROR_SIGNALSOURCE_SETTINGFAILED,
	// 串口
	ERROR_SERIALPORT_CONNECTIONFAILED,
	// TCP
	ERROR_TCP_CONNECTIONFAILED,
	// UDP
	ERROR_UDP_CONNECTIONFAILED,
	// 相机
	ERROR_CAMERA_COMMUNICATIONFAILURE,
	ERROR_CAMERA_RECOGNITIONFAILED,
	ERROR_CAMERA_WRITEFAILED,
	ERROR_CAMERA_READFAILED,
	// 流程
	ERROR_PROCESS_GROUPLOSS,
	ERROR_PROCESS_OUTOFNESTING,
	ERROR_PROCESS_AXISOUTOFLIMIT,
	ERROR_PROCESS_AXISDISABLED,
	ERROR_PROCESS_LASERSETFAILED,
	ERROR_PROCESS_CUTOUTOFLIMIT,
	ERROR_PROCESS_NONECOMMANDSFILE,
	ERROR_PROCESS_COMMANDSINVALID,
	ERROR_PROCESS_IOINVALID,
	ERROR_PROCESS_GROUPTIMEOUT,
	ERROR_PROCESS_GROUPRUNNING,
	ERROR_PROCESS_IFTIMEOUT,
	ERROR_PROCESS_OUTOFTOLERANCE,
	// 切割
	ERROR_CUTTING_LISTEMPTY,
	ERROR_CUTTING_SENDCOMMAND,
	ERROR_CUTTING_CREATLIST,
	ERROR_CUTTING_OUTOFLIMIT,
	ERROR_CUTTING_OVERTIME,
	ERROR_CUTTING_GETCOMPENSATIONFAILED,
	// 超行程切割
	ERROR_OVERCUTTING_NODIVISIONLAYER,
	ERROR_OVERCUTTING_DIVISIONLAYERERR,
	ERROR_OVERCUTTING_DIVISIONEMPTY,
	ERROR_OVERCUTTING_NOCUTENTITY,
	ERROR_OVERCUTTING_OUTOFLIMIT,
	ERROR_OVERCUTTING_LSUG_TOO_LARGE,
	ERROR_OVERCUTTING_NOGAPINLIMIT,
	ERROR_OVERCUTTING_SEGTOOSHORT,
	ERROR_OVERCUTTING_LIMITNOTREADY,	// X 轴限位尚未就绪（设备未初始化完成）
	ERROR_OVERCUTTING_INVALIDRANGE,		// 图元 X 范围退化（endX<=startX）
	// 自动寻焦
	ERROR_AUTOFOCUS_NOFOCUSLAYER,
	ERROR_AUTOFOCUS_NOODDNUMBER,
	// 监控
	ERROR_MONITOR,
	ERROR_MONITOR_AXISDISABLED,
	ERROR_MONITOR_WATERLEAKAGE,
	ERROR_MONITOR_WATERTANK,
	ERROR_MONITOR_PRESSURE,
	// 设置
	ERROR_SETTING_,
	// 文件
	ERROR_FILE_INVALIDCONTENT,
	// 计算
	ERROR_EXPRES_NONEEXPRESSION,	//空解析式
	ERROR_EXPRES_EXPRESSIONINVALID,	//解析失败
	ERROR_EXPRES_CALCULATIONFAILED,	//计算失败
	ERROR_EXPRES_NONEINDEX,			//无效索引
	// 特殊
	ERROR_SPECIAL_LPCONNECTIONFAILED,	//LP连接失败
	ERROR_SPECIAL_LPSENDFAILED,			//LP发送失败
	ERROR_SPECIAL_LPRESPONSENONE,		//LP返回无效索引
	ERROR_SPECIAL_LPNONEINDEX			//LP无效索引
};

// 警告
enum class WarnCode
{
	WARN_NONE = 0,
	// 系统
	WARN_SYSTEM_,
	// 运动控制器
	WARN_MC_DISCONNECTED,
	WARN_MC_OUTOFLIMIT,
	WARN_MC_NONEINDEX,
	// 激光器
	WARN_LASER_DISCONNECTED,
	// 信号源
	WARN_SIGNALSOURCE_,
	// 串口
	WARN_SERIALPORT_,
	// 流程
	WARN_PROCESS_ITEMEDITING,
	// 切割
	WARN_CUTTING_,
	// 监控
	WARN_MONITOR_INTERLOCK,
	WARN_MONITOR_PRESSURE,
	WARN_MONITOR_WATERPRESSURE,
	WARN_MONITOR_SAFETYLIGHTCURTAIN, 
	// 设置
	WARN_SETTING_SAMETOOLNAME,
	WARN_SETTING_ONLYONETOOL,
	WARN_SETTING_IMPORTTOOL,
	// 文件
	WARN_FILE_OPENFAILD,
	WARN_FILE_IMPORTFAILD,
	WARN_FILE_EXPORTFAILD,
	WARN_FILE_INVALIDCONTENT,
	//寻焦
	WARN_FOCUS_CREATFILEERR,
	WARN_FOCUS_MCNOTREADY
};

// 提示
enum class InfoCode
{
	INFO_NONE = 0,
	// 系统
	INFO_SYSTEM_,
	// 运动控制器
	INFO_MC_,
	// 激光器
	INFO_LASER_,
	// 信号源
	INFO_SIGNALSOURCE_,
	// 串口
	INFO_SERIALPORT_,
	// 流程
	INFO_PROCESS_SEQUENCEZERO,
	// 切割
	INFO_CUTTING_,
	// 监控
	INFO_MONITOR_WATERLEVEL,
	// 设置
	INFO_SETTING_,
	// 文件
	INFO_FILE_NONEENTITY,
	INFO_FILE_NONESETTINGS,
	INFO_FILE_NONEPROCESS
};